/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for AuthorizeRequest type.
 */
public class AuthorizeRequest {
    private PaymentSourceDefinition paymentSource;

    /**
     * Default constructor.
     */
    public AuthorizeRequest() {
    }

    /**
     * Initialization constructor.
     * @param  paymentSource  PaymentSourceDefinition value for paymentSource.
     */
    public AuthorizeRequest(
            PaymentSourceDefinition paymentSource) {
        this.paymentSource = paymentSource;
    }

    /**
     * Getter for PaymentSource.
     * The source of payment for the order, which can be a token or a card. Use this object only if
     * you have not redirected the user after order creation to approve the payment. In such cases,
     * the user-selected payment method in the PayPal flow is implicitly used.
     * @return Returns the PaymentSourceDefinition
     */
    @JsonGetter("payment_source")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PaymentSourceDefinition getPaymentSource() {
        return paymentSource;
    }

    /**
     * Setter for PaymentSource.
     * The source of payment for the order, which can be a token or a card. Use this object only if
     * you have not redirected the user after order creation to approve the payment. In such cases,
     * the user-selected payment method in the PayPal flow is implicitly used.
     * @param paymentSource Value for PaymentSourceDefinition
     */
    @JsonSetter("payment_source")
    public void setPaymentSource(PaymentSourceDefinition paymentSource) {
        this.paymentSource = paymentSource;
    }

    /**
     * Converts this AuthorizeRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AuthorizeRequest [" + "paymentSource=" + paymentSource + "]";
    }

    /**
     * Builds a new {@link AuthorizeRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AuthorizeRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .paymentSource(getPaymentSource());
        return builder;
    }

    /**
     * Class to build instances of {@link AuthorizeRequest}.
     */
    public static class Builder {
        private PaymentSourceDefinition paymentSource;



        /**
         * Setter for paymentSource.
         * @param  paymentSource  PaymentSourceDefinition value for paymentSource.
         * @return Builder
         */
        public Builder paymentSource(PaymentSourceDefinition paymentSource) {
            this.paymentSource = paymentSource;
            return this;
        }

        /**
         * Builds a new {@link AuthorizeRequest} object using the set fields.
         * @return {@link AuthorizeRequest}
         */
        public AuthorizeRequest build() {
            return new AuthorizeRequest(paymentSource);
        }
    }
}
