/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * AuthorizationCurrencyMismatchDescriptionEnum to be used.
 */
public enum AuthorizationCurrencyMismatchDescriptionEnum {
    ENUM_THE_CURRENCY_OF_THE_AUTHORIZATION_SHOULD_BE_SAME_AS_THAT_IN_WHICH_THE_ORDER_WAS_CREATED_AND_APPROVED_BY_THE_PAYER_PLEASE_CHECK_THE_CURRENCY_CODE_AND_TRY_AGAIN;


    private static TreeMap<String, AuthorizationCurrencyMismatchDescriptionEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_THE_CURRENCY_OF_THE_AUTHORIZATION_SHOULD_BE_SAME_AS_THAT_IN_WHICH_THE_ORDER_WAS_CREATED_AND_APPROVED_BY_THE_PAYER_PLEASE_CHECK_THE_CURRENCY_CODE_AND_TRY_AGAIN.value = "The currency of the authorization should be same as that in which the Order was created and approved by the Payer. Please check the 'currency_code' and try again.";

        valueMap.put("The currency of the authorization should be same as that in which the Order was created and approved by the Payer. Please check the 'currency_code' and try again.", ENUM_THE_CURRENCY_OF_THE_AUTHORIZATION_SHOULD_BE_SAME_AS_THAT_IN_WHICH_THE_ORDER_WAS_CREATED_AND_APPROVED_BY_THE_PAYER_PLEASE_CHECK_THE_CURRENCY_CODE_AND_TRY_AGAIN);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static AuthorizationCurrencyMismatchDescriptionEnum constructFromString(String toConvert) throws IOException {
        AuthorizationCurrencyMismatchDescriptionEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static AuthorizationCurrencyMismatchDescriptionEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of AuthorizationCurrencyMismatchDescriptionEnum values to list of string values.
     * @param toConvert The list of AuthorizationCurrencyMismatchDescriptionEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<AuthorizationCurrencyMismatchDescriptionEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (AuthorizationCurrencyMismatchDescriptionEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 