/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * AuthCaptureCurrencyMismatchDescriptionEnum to be used.
 */
public enum AuthCaptureCurrencyMismatchDescriptionEnum {
    ENUM_CURRENCY_OF_CAPTURE_MUST_BE_THE_SAME_AS_CURRENCY_OF_AUTHORIZATION;


    private static TreeMap<String, AuthCaptureCurrencyMismatchDescriptionEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_CURRENCY_OF_CAPTURE_MUST_BE_THE_SAME_AS_CURRENCY_OF_AUTHORIZATION.value = "Currency of capture must be the same as currency of authorization.";

        valueMap.put("Currency of capture must be the same as currency of authorization.", ENUM_CURRENCY_OF_CAPTURE_MUST_BE_THE_SAME_AS_CURRENCY_OF_AUTHORIZATION);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static AuthCaptureCurrencyMismatchDescriptionEnum constructFromString(String toConvert) throws IOException {
        AuthCaptureCurrencyMismatchDescriptionEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static AuthCaptureCurrencyMismatchDescriptionEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of AuthCaptureCurrencyMismatchDescriptionEnum values to list of string values.
     * @param toConvert The list of AuthCaptureCurrencyMismatchDescriptionEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<AuthCaptureCurrencyMismatchDescriptionEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (AuthCaptureCurrencyMismatchDescriptionEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 