/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * BadRequestMessageEnum to be used.
 */
public enum BadRequestMessageEnum {
    ENUM_REQUEST_IS_NOT_WELLFORMED_SYNTACTICALLY_INCORRECT_OR_VIOLATES_SCHEMA;


    private static TreeMap<String, BadRequestMessageEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_REQUEST_IS_NOT_WELLFORMED_SYNTACTICALLY_INCORRECT_OR_VIOLATES_SCHEMA.value = "Request is not well-formed, syntactically incorrect, or violates schema.";

        valueMap.put("Request is not well-formed, syntactically incorrect, or violates schema.", ENUM_REQUEST_IS_NOT_WELLFORMED_SYNTACTICALLY_INCORRECT_OR_VIOLATES_SCHEMA);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static BadRequestMessageEnum constructFromString(String toConvert) throws IOException {
        BadRequestMessageEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static BadRequestMessageEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of BadRequestMessageEnum values to list of string values.
     * @param toConvert The list of BadRequestMessageEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<BadRequestMessageEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (BadRequestMessageEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 