/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Badrequest400errorresponseissuesItems type.
 */
public class Badrequest400errorresponseissuesItems {
    private InvalidParameterValueIssueEnum issue;
    private InvalidParameterValueDescriptionPaymentsEnum description;

    /**
     * Default constructor.
     */
    public Badrequest400errorresponseissuesItems() {
    }

    /**
     * Initialization constructor.
     * @param  issue  InvalidParameterValueIssueEnum value for issue.
     * @param  description  InvalidParameterValueDescriptionPaymentsEnum value for description.
     */
    public Badrequest400errorresponseissuesItems(
            InvalidParameterValueIssueEnum issue,
            InvalidParameterValueDescriptionPaymentsEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the InvalidParameterValueIssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public InvalidParameterValueIssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for InvalidParameterValueIssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(InvalidParameterValueIssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the InvalidParameterValueDescriptionPaymentsEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public InvalidParameterValueDescriptionPaymentsEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for InvalidParameterValueDescriptionPaymentsEnum
     */
    @JsonSetter("description")
    public void setDescription(InvalidParameterValueDescriptionPaymentsEnum description) {
        this.description = description;
    }

    /**
     * Converts this Badrequest400errorresponseissuesItems into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Badrequest400errorresponseissuesItems [" + "issue=" + issue + ", description="
                + description + "]";
    }

    /**
     * Builds a new {@link Badrequest400errorresponseissuesItems.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Badrequest400errorresponseissuesItems.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link Badrequest400errorresponseissuesItems}.
     */
    public static class Builder {
        private InvalidParameterValueIssueEnum issue;
        private InvalidParameterValueDescriptionPaymentsEnum description;



        /**
         * Setter for issue.
         * @param  issue  InvalidParameterValueIssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(InvalidParameterValueIssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  InvalidParameterValueDescriptionPaymentsEnum value for description.
         * @return Builder
         */
        public Builder description(InvalidParameterValueDescriptionPaymentsEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link Badrequest400errorresponseissuesItems} object using the set fields.
         * @return {@link Badrequest400errorresponseissuesItems}
         */
        public Badrequest400errorresponseissuesItems build() {
            return new Badrequest400errorresponseissuesItems(issue, description);
        }
    }
}
