/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for BANKNOTSUPPORTEDFORVERIFICATIONERROR type.
 */
public class BANKNOTSUPPORTEDFORVERIFICATIONERROR {
    private BankNotSupportedForVerification1IssueEnum issue;
    private BankNotSupportedForVerification1DescriptionEnum description;

    /**
     * Default constructor.
     */
    public BANKNOTSUPPORTEDFORVERIFICATIONERROR() {
    }

    /**
     * Initialization constructor.
     * @param  issue  BankNotSupportedForVerification1IssueEnum value for issue.
     * @param  description  BankNotSupportedForVerification1DescriptionEnum value for description.
     */
    public BANKNOTSUPPORTEDFORVERIFICATIONERROR(
            BankNotSupportedForVerification1IssueEnum issue,
            BankNotSupportedForVerification1DescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the BankNotSupportedForVerification1IssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public BankNotSupportedForVerification1IssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for BankNotSupportedForVerification1IssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(BankNotSupportedForVerification1IssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the BankNotSupportedForVerification1DescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public BankNotSupportedForVerification1DescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for BankNotSupportedForVerification1DescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(BankNotSupportedForVerification1DescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this BANKNOTSUPPORTEDFORVERIFICATIONERROR into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BANKNOTSUPPORTEDFORVERIFICATIONERROR [" + "issue=" + issue + ", description="
                + description + "]";
    }

    /**
     * Builds a new {@link BANKNOTSUPPORTEDFORVERIFICATIONERROR.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BANKNOTSUPPORTEDFORVERIFICATIONERROR.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link BANKNOTSUPPORTEDFORVERIFICATIONERROR}.
     */
    public static class Builder {
        private BankNotSupportedForVerification1IssueEnum issue;
        private BankNotSupportedForVerification1DescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  BankNotSupportedForVerification1IssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(BankNotSupportedForVerification1IssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  BankNotSupportedForVerification1DescriptionEnum value for
         *         description.
         * @return Builder
         */
        public Builder description(BankNotSupportedForVerification1DescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link BANKNOTSUPPORTEDFORVERIFICATIONERROR} object using the set fields.
         * @return {@link BANKNOTSUPPORTEDFORVERIFICATIONERROR}
         */
        public BANKNOTSUPPORTEDFORVERIFICATIONERROR build() {
            return new BANKNOTSUPPORTEDFORVERIFICATIONERROR(issue, description);
        }
    }
}
