/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for BILLINGAGREEMENTNOTFOUND type.
 */
public class BILLINGAGREEMENTNOTFOUND {
    private BillingAgreementNotFoundIssueEnum issue;
    private BillingAgreementNotFoundDescriptionEnum description;

    /**
     * Default constructor.
     */
    public BILLINGAGREEMENTNOTFOUND() {
    }

    /**
     * Initialization constructor.
     * @param  issue  BillingAgreementNotFoundIssueEnum value for issue.
     * @param  description  BillingAgreementNotFoundDescriptionEnum value for description.
     */
    public BILLINGAGREEMENTNOTFOUND(
            BillingAgreementNotFoundIssueEnum issue,
            BillingAgreementNotFoundDescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the BillingAgreementNotFoundIssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public BillingAgreementNotFoundIssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for BillingAgreementNotFoundIssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(BillingAgreementNotFoundIssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the BillingAgreementNotFoundDescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public BillingAgreementNotFoundDescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for BillingAgreementNotFoundDescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(BillingAgreementNotFoundDescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this BILLINGAGREEMENTNOTFOUND into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BILLINGAGREEMENTNOTFOUND [" + "issue=" + issue + ", description=" + description
                + "]";
    }

    /**
     * Builds a new {@link BILLINGAGREEMENTNOTFOUND.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BILLINGAGREEMENTNOTFOUND.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link BILLINGAGREEMENTNOTFOUND}.
     */
    public static class Builder {
        private BillingAgreementNotFoundIssueEnum issue;
        private BillingAgreementNotFoundDescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  BillingAgreementNotFoundIssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(BillingAgreementNotFoundIssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  BillingAgreementNotFoundDescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(BillingAgreementNotFoundDescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link BILLINGAGREEMENTNOTFOUND} object using the set fields.
         * @return {@link BILLINGAGREEMENTNOTFOUND}
         */
        public BILLINGAGREEMENTNOTFOUND build() {
            return new BILLINGAGREEMENTNOTFOUND(issue, description);
        }
    }
}
