/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for BILLINGAGREEMENTIDMISMATCHERROR type.
 */
public class BILLINGAGREEMENTIDMISMATCHERROR {
    private BillingAgreementIdMismatch1IssueEnum issue;
    private BillingAgreementIdMismatch1DescriptionEnum description;

    /**
     * Default constructor.
     */
    public BILLINGAGREEMENTIDMISMATCHERROR() {
    }

    /**
     * Initialization constructor.
     * @param  issue  BillingAgreementIdMismatch1IssueEnum value for issue.
     * @param  description  BillingAgreementIdMismatch1DescriptionEnum value for description.
     */
    public BILLINGAGREEMENTIDMISMATCHERROR(
            BillingAgreementIdMismatch1IssueEnum issue,
            BillingAgreementIdMismatch1DescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the BillingAgreementIdMismatch1IssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public BillingAgreementIdMismatch1IssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for BillingAgreementIdMismatch1IssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(BillingAgreementIdMismatch1IssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the BillingAgreementIdMismatch1DescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public BillingAgreementIdMismatch1DescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for BillingAgreementIdMismatch1DescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(BillingAgreementIdMismatch1DescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this BILLINGAGREEMENTIDMISMATCHERROR into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BILLINGAGREEMENTIDMISMATCHERROR [" + "issue=" + issue + ", description="
                + description + "]";
    }

    /**
     * Builds a new {@link BILLINGAGREEMENTIDMISMATCHERROR.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BILLINGAGREEMENTIDMISMATCHERROR.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link BILLINGAGREEMENTIDMISMATCHERROR}.
     */
    public static class Builder {
        private BillingAgreementIdMismatch1IssueEnum issue;
        private BillingAgreementIdMismatch1DescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  BillingAgreementIdMismatch1IssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(BillingAgreementIdMismatch1IssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  BillingAgreementIdMismatch1DescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(BillingAgreementIdMismatch1DescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link BILLINGAGREEMENTIDMISMATCHERROR} object using the set fields.
         * @return {@link BILLINGAGREEMENTIDMISMATCHERROR}
         */
        public BILLINGAGREEMENTIDMISMATCHERROR build() {
            return new BILLINGAGREEMENTIDMISMATCHERROR(issue, description);
        }
    }
}
