/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for BLIKONECLICKMISSINGREQUIREDPARAMETER type.
 */
public class BLIKONECLICKMISSINGREQUIREDPARAMETER {
    private BlikOneClickMissingRequiredParameterIssueEnum issue;
    private OneClickFirstTransactionParamsEnum description;

    /**
     * Default constructor.
     */
    public BLIKONECLICKMISSINGREQUIREDPARAMETER() {
    }

    /**
     * Initialization constructor.
     * @param  issue  BlikOneClickMissingRequiredParameterIssueEnum value for issue.
     * @param  description  OneClickFirstTransactionParamsEnum value for description.
     */
    public BLIKONECLICKMISSINGREQUIREDPARAMETER(
            BlikOneClickMissingRequiredParameterIssueEnum issue,
            OneClickFirstTransactionParamsEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the BlikOneClickMissingRequiredParameterIssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public BlikOneClickMissingRequiredParameterIssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for BlikOneClickMissingRequiredParameterIssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(BlikOneClickMissingRequiredParameterIssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the OneClickFirstTransactionParamsEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public OneClickFirstTransactionParamsEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for OneClickFirstTransactionParamsEnum
     */
    @JsonSetter("description")
    public void setDescription(OneClickFirstTransactionParamsEnum description) {
        this.description = description;
    }

    /**
     * Converts this BLIKONECLICKMISSINGREQUIREDPARAMETER into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BLIKONECLICKMISSINGREQUIREDPARAMETER [" + "issue=" + issue + ", description="
                + description + "]";
    }

    /**
     * Builds a new {@link BLIKONECLICKMISSINGREQUIREDPARAMETER.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BLIKONECLICKMISSINGREQUIREDPARAMETER.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link BLIKONECLICKMISSINGREQUIREDPARAMETER}.
     */
    public static class Builder {
        private BlikOneClickMissingRequiredParameterIssueEnum issue;
        private OneClickFirstTransactionParamsEnum description;



        /**
         * Setter for issue.
         * @param  issue  BlikOneClickMissingRequiredParameterIssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(BlikOneClickMissingRequiredParameterIssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  OneClickFirstTransactionParamsEnum value for description.
         * @return Builder
         */
        public Builder description(OneClickFirstTransactionParamsEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link BLIKONECLICKMISSINGREQUIREDPARAMETER} object using the set fields.
         * @return {@link BLIKONECLICKMISSINGREQUIREDPARAMETER}
         */
        public BLIKONECLICKMISSINGREQUIREDPARAMETER build() {
            return new BLIKONECLICKMISSINGREQUIREDPARAMETER(issue, description);
        }
    }
}
