/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CANCELURLREQUIRED type.
 */
public class CANCELURLREQUIRED {
    private CancelUrlRequiredIssueEnum issue;
    private CancelUrlRequiredDescriptionEnum description;

    /**
     * Default constructor.
     */
    public CANCELURLREQUIRED() {
    }

    /**
     * Initialization constructor.
     * @param  issue  CancelUrlRequiredIssueEnum value for issue.
     * @param  description  CancelUrlRequiredDescriptionEnum value for description.
     */
    public CANCELURLREQUIRED(
            CancelUrlRequiredIssueEnum issue,
            CancelUrlRequiredDescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the CancelUrlRequiredIssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CancelUrlRequiredIssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for CancelUrlRequiredIssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(CancelUrlRequiredIssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the CancelUrlRequiredDescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CancelUrlRequiredDescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for CancelUrlRequiredDescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(CancelUrlRequiredDescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this CANCELURLREQUIRED into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CANCELURLREQUIRED [" + "issue=" + issue + ", description=" + description + "]";
    }

    /**
     * Builds a new {@link CANCELURLREQUIRED.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CANCELURLREQUIRED.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link CANCELURLREQUIRED}.
     */
    public static class Builder {
        private CancelUrlRequiredIssueEnum issue;
        private CancelUrlRequiredDescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  CancelUrlRequiredIssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(CancelUrlRequiredIssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  CancelUrlRequiredDescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(CancelUrlRequiredDescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link CANCELURLREQUIRED} object using the set fields.
         * @return {@link CANCELURLREQUIRED}
         */
        public CANCELURLREQUIRED build() {
            return new CANCELURLREQUIRED(issue, description);
        }
    }
}
