/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * CapturesRefund422IssuesItemsAnyof10DescriptionEnum to be used.
 */
public enum CapturesRefund422IssuesItemsAnyof10DescriptionEnum {
    ENUM_THE_REFUND_AMOUNT_MUST_BE_LESS_THAN_OR_EQUAL_TO_THE_CAPTURE_AMOUNT_THAT_HAS_NOT_YET_BEEN_REFUNDED;


    private static TreeMap<String, CapturesRefund422IssuesItemsAnyof10DescriptionEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_THE_REFUND_AMOUNT_MUST_BE_LESS_THAN_OR_EQUAL_TO_THE_CAPTURE_AMOUNT_THAT_HAS_NOT_YET_BEEN_REFUNDED.value = "The refund amount must be less than or equal to the capture amount that has not yet been refunded.";

        valueMap.put("The refund amount must be less than or equal to the capture amount that has not yet been refunded.", ENUM_THE_REFUND_AMOUNT_MUST_BE_LESS_THAN_OR_EQUAL_TO_THE_CAPTURE_AMOUNT_THAT_HAS_NOT_YET_BEEN_REFUNDED);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static CapturesRefund422IssuesItemsAnyof10DescriptionEnum constructFromString(String toConvert) throws IOException {
        CapturesRefund422IssuesItemsAnyof10DescriptionEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static CapturesRefund422IssuesItemsAnyof10DescriptionEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of CapturesRefund422IssuesItemsAnyof10DescriptionEnum values to list of string values.
     * @param toConvert The list of CapturesRefund422IssuesItemsAnyof10DescriptionEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<CapturesRefund422IssuesItemsAnyof10DescriptionEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (CapturesRefund422IssuesItemsAnyof10DescriptionEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 