/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CARDBRANDNOTSUPPORTED type.
 */
public class CARDBRANDNOTSUPPORTED {
    private CardBrandNotSupportedIssueEnum issue;
    private CardBrandNotSupportedDescriptionEnum description;

    /**
     * Default constructor.
     */
    public CARDBRANDNOTSUPPORTED() {
    }

    /**
     * Initialization constructor.
     * @param  issue  CardBrandNotSupportedIssueEnum value for issue.
     * @param  description  CardBrandNotSupportedDescriptionEnum value for description.
     */
    public CARDBRANDNOTSUPPORTED(
            CardBrandNotSupportedIssueEnum issue,
            CardBrandNotSupportedDescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the CardBrandNotSupportedIssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CardBrandNotSupportedIssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for CardBrandNotSupportedIssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(CardBrandNotSupportedIssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the CardBrandNotSupportedDescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CardBrandNotSupportedDescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for CardBrandNotSupportedDescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(CardBrandNotSupportedDescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this CARDBRANDNOTSUPPORTED into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CARDBRANDNOTSUPPORTED [" + "issue=" + issue + ", description=" + description + "]";
    }

    /**
     * Builds a new {@link CARDBRANDNOTSUPPORTED.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CARDBRANDNOTSUPPORTED.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link CARDBRANDNOTSUPPORTED}.
     */
    public static class Builder {
        private CardBrandNotSupportedIssueEnum issue;
        private CardBrandNotSupportedDescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  CardBrandNotSupportedIssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(CardBrandNotSupportedIssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  CardBrandNotSupportedDescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(CardBrandNotSupportedDescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link CARDBRANDNOTSUPPORTED} object using the set fields.
         * @return {@link CARDBRANDNOTSUPPORTED}
         */
        public CARDBRANDNOTSUPPORTED build() {
            return new CARDBRANDNOTSUPPORTED(issue, description);
        }
    }
}
