/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CARDTYPENOTSUPPORTED type.
 */
public class CARDTYPENOTSUPPORTED {
    private CardTypeNotSupportedIssueEnum issue;
    private CardTypeNotSupportedDescriptionEnum description;

    /**
     * Default constructor.
     */
    public CARDTYPENOTSUPPORTED() {
    }

    /**
     * Initialization constructor.
     * @param  issue  CardTypeNotSupportedIssueEnum value for issue.
     * @param  description  CardTypeNotSupportedDescriptionEnum value for description.
     */
    public CARDTYPENOTSUPPORTED(
            CardTypeNotSupportedIssueEnum issue,
            CardTypeNotSupportedDescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the CardTypeNotSupportedIssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CardTypeNotSupportedIssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for CardTypeNotSupportedIssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(CardTypeNotSupportedIssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the CardTypeNotSupportedDescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CardTypeNotSupportedDescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for CardTypeNotSupportedDescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(CardTypeNotSupportedDescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this CARDTYPENOTSUPPORTED into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CARDTYPENOTSUPPORTED [" + "issue=" + issue + ", description=" + description + "]";
    }

    /**
     * Builds a new {@link CARDTYPENOTSUPPORTED.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CARDTYPENOTSUPPORTED.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link CARDTYPENOTSUPPORTED}.
     */
    public static class Builder {
        private CardTypeNotSupportedIssueEnum issue;
        private CardTypeNotSupportedDescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  CardTypeNotSupportedIssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(CardTypeNotSupportedIssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  CardTypeNotSupportedDescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(CardTypeNotSupportedDescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link CARDTYPENOTSUPPORTED} object using the set fields.
         * @return {@link CARDTYPENOTSUPPORTED}
         */
        public CARDTYPENOTSUPPORTED build() {
            return new CARDTYPENOTSUPPORTED(issue, description);
        }
    }
}
