/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CHARGEBACKONPREVIOUSTRANSACTIONERROR type.
 */
public class CHARGEBACKONPREVIOUSTRANSACTIONERROR {
    private PreviousTransactionReferenceChargebackIssue1Enum issue;
    private CaptureWithChargebackNotUsableDescEnum description;

    /**
     * Default constructor.
     */
    public CHARGEBACKONPREVIOUSTRANSACTIONERROR() {
    }

    /**
     * Initialization constructor.
     * @param  issue  PreviousTransactionReferenceChargebackIssue1Enum value for issue.
     * @param  description  CaptureWithChargebackNotUsableDescEnum value for description.
     */
    public CHARGEBACKONPREVIOUSTRANSACTIONERROR(
            PreviousTransactionReferenceChargebackIssue1Enum issue,
            CaptureWithChargebackNotUsableDescEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the PreviousTransactionReferenceChargebackIssue1Enum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PreviousTransactionReferenceChargebackIssue1Enum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for PreviousTransactionReferenceChargebackIssue1Enum
     */
    @JsonSetter("issue")
    public void setIssue(PreviousTransactionReferenceChargebackIssue1Enum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the CaptureWithChargebackNotUsableDescEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CaptureWithChargebackNotUsableDescEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for CaptureWithChargebackNotUsableDescEnum
     */
    @JsonSetter("description")
    public void setDescription(CaptureWithChargebackNotUsableDescEnum description) {
        this.description = description;
    }

    /**
     * Converts this CHARGEBACKONPREVIOUSTRANSACTIONERROR into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CHARGEBACKONPREVIOUSTRANSACTIONERROR [" + "issue=" + issue + ", description="
                + description + "]";
    }

    /**
     * Builds a new {@link CHARGEBACKONPREVIOUSTRANSACTIONERROR.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CHARGEBACKONPREVIOUSTRANSACTIONERROR.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link CHARGEBACKONPREVIOUSTRANSACTIONERROR}.
     */
    public static class Builder {
        private PreviousTransactionReferenceChargebackIssue1Enum issue;
        private CaptureWithChargebackNotUsableDescEnum description;



        /**
         * Setter for issue.
         * @param  issue  PreviousTransactionReferenceChargebackIssue1Enum value for issue.
         * @return Builder
         */
        public Builder issue(PreviousTransactionReferenceChargebackIssue1Enum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  CaptureWithChargebackNotUsableDescEnum value for description.
         * @return Builder
         */
        public Builder description(CaptureWithChargebackNotUsableDescEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link CHARGEBACKONPREVIOUSTRANSACTIONERROR} object using the set fields.
         * @return {@link CHARGEBACKONPREVIOUSTRANSACTIONERROR}
         */
        public CHARGEBACKONPREVIOUSTRANSACTIONERROR build() {
            return new CHARGEBACKONPREVIOUSTRANSACTIONERROR(issue, description);
        }
    }
}
