/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for COMPLIANCEVIOLATIONERROR type.
 */
public class COMPLIANCEVIOLATIONERROR {
    private ComplianceViolation1IssueEnum issue;
    private ComplianceViolation1DescriptionEnum description;

    /**
     * Default constructor.
     */
    public COMPLIANCEVIOLATIONERROR() {
    }

    /**
     * Initialization constructor.
     * @param  issue  ComplianceViolation1IssueEnum value for issue.
     * @param  description  ComplianceViolation1DescriptionEnum value for description.
     */
    public COMPLIANCEVIOLATIONERROR(
            ComplianceViolation1IssueEnum issue,
            ComplianceViolation1DescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the ComplianceViolation1IssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ComplianceViolation1IssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for ComplianceViolation1IssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(ComplianceViolation1IssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the ComplianceViolation1DescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ComplianceViolation1DescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for ComplianceViolation1DescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(ComplianceViolation1DescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this COMPLIANCEVIOLATIONERROR into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "COMPLIANCEVIOLATIONERROR [" + "issue=" + issue + ", description=" + description
                + "]";
    }

    /**
     * Builds a new {@link COMPLIANCEVIOLATIONERROR.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link COMPLIANCEVIOLATIONERROR.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link COMPLIANCEVIOLATIONERROR}.
     */
    public static class Builder {
        private ComplianceViolation1IssueEnum issue;
        private ComplianceViolation1DescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  ComplianceViolation1IssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(ComplianceViolation1IssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  ComplianceViolation1DescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(ComplianceViolation1DescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link COMPLIANCEVIOLATIONERROR} object using the set fields.
         * @return {@link COMPLIANCEVIOLATIONERROR}
         */
        public COMPLIANCEVIOLATIONERROR build() {
            return new COMPLIANCEVIOLATIONERROR(issue, description);
        }
    }
}
