/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for DECLINEDDUETORELATEDTXNERROR type.
 */
public class DECLINEDDUETORELATEDTXNERROR {
    private DeclinedDueToRelatedTxn1IssueEnum issue;
    private DeclinedDueToRelatedTxn1DescriptionEnum description;

    /**
     * Default constructor.
     */
    public DECLINEDDUETORELATEDTXNERROR() {
    }

    /**
     * Initialization constructor.
     * @param  issue  DeclinedDueToRelatedTxn1IssueEnum value for issue.
     * @param  description  DeclinedDueToRelatedTxn1DescriptionEnum value for description.
     */
    public DECLINEDDUETORELATEDTXNERROR(
            DeclinedDueToRelatedTxn1IssueEnum issue,
            DeclinedDueToRelatedTxn1DescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the DeclinedDueToRelatedTxn1IssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public DeclinedDueToRelatedTxn1IssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for DeclinedDueToRelatedTxn1IssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(DeclinedDueToRelatedTxn1IssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the DeclinedDueToRelatedTxn1DescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public DeclinedDueToRelatedTxn1DescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for DeclinedDueToRelatedTxn1DescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(DeclinedDueToRelatedTxn1DescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this DECLINEDDUETORELATEDTXNERROR into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DECLINEDDUETORELATEDTXNERROR [" + "issue=" + issue + ", description=" + description
                + "]";
    }

    /**
     * Builds a new {@link DECLINEDDUETORELATEDTXNERROR.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DECLINEDDUETORELATEDTXNERROR.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link DECLINEDDUETORELATEDTXNERROR}.
     */
    public static class Builder {
        private DeclinedDueToRelatedTxn1IssueEnum issue;
        private DeclinedDueToRelatedTxn1DescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  DeclinedDueToRelatedTxn1IssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(DeclinedDueToRelatedTxn1IssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  DeclinedDueToRelatedTxn1DescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(DeclinedDueToRelatedTxn1DescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link DECLINEDDUETORELATEDTXNERROR} object using the set fields.
         * @return {@link DECLINEDDUETORELATEDTXNERROR}
         */
        public DECLINEDDUETORELATEDTXNERROR build() {
            return new DECLINEDDUETORELATEDTXNERROR(issue, description);
        }
    }
}
