/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * DuplicateInvoiceIdDescriptionPaymentsEnum to be used.
 */
public enum DuplicateInvoiceIdDescriptionPaymentsEnum {
    ENUM_REQUESTED_INVOICE_ID_HAS_BEEN_PREVIOUSLY_CAPTURED_POSSIBLE_DUPLICATE_TRANSACTION;


    private static TreeMap<String, DuplicateInvoiceIdDescriptionPaymentsEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_REQUESTED_INVOICE_ID_HAS_BEEN_PREVIOUSLY_CAPTURED_POSSIBLE_DUPLICATE_TRANSACTION.value = "Requested invoice_id has been previously captured. Possible duplicate transaction.";

        valueMap.put("Requested invoice_id has been previously captured. Possible duplicate transaction.", ENUM_REQUESTED_INVOICE_ID_HAS_BEEN_PREVIOUSLY_CAPTURED_POSSIBLE_DUPLICATE_TRANSACTION);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static DuplicateInvoiceIdDescriptionPaymentsEnum constructFromString(String toConvert) throws IOException {
        DuplicateInvoiceIdDescriptionPaymentsEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static DuplicateInvoiceIdDescriptionPaymentsEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of DuplicateInvoiceIdDescriptionPaymentsEnum values to list of string values.
     * @param toConvert The list of DuplicateInvoiceIdDescriptionPaymentsEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<DuplicateInvoiceIdDescriptionPaymentsEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (DuplicateInvoiceIdDescriptionPaymentsEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 