/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * EmvDataRequired1DescriptionEnum to be used.
 */
public enum EmvDataRequired1DescriptionEnum {
    ENUM_EMV_DATA_IS_REQUIRED_IF_AUTHENTICATION_METHOD_IS_EMV;


    private static TreeMap<String, EmvDataRequired1DescriptionEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_EMV_DATA_IS_REQUIRED_IF_AUTHENTICATION_METHOD_IS_EMV.value = "EMV Data is required if authentication method is EMV.";

        valueMap.put("EMV Data is required if authentication method is EMV.", ENUM_EMV_DATA_IS_REQUIRED_IF_AUTHENTICATION_METHOD_IS_EMV);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static EmvDataRequired1DescriptionEnum constructFromString(String toConvert) throws IOException {
        EmvDataRequired1DescriptionEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static EmvDataRequired1DescriptionEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of EmvDataRequired1DescriptionEnum values to list of string values.
     * @param toConvert The list of EmvDataRequired1DescriptionEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<EmvDataRequired1DescriptionEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (EmvDataRequired1DescriptionEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 