/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * HttpMethodEnum to be used.
 */
public enum HttpMethodEnum {
    GET,

    POST,

    PUT,

    DELETE,

    HEAD,

    CONNECT,

    OPTIONS,

    PATCH;


    private static TreeMap<String, HttpMethodEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        GET.value = "GET";
        POST.value = "POST";
        PUT.value = "PUT";
        DELETE.value = "DELETE";
        HEAD.value = "HEAD";
        CONNECT.value = "CONNECT";
        OPTIONS.value = "OPTIONS";
        PATCH.value = "PATCH";

        valueMap.put("GET", GET);
        valueMap.put("POST", POST);
        valueMap.put("PUT", PUT);
        valueMap.put("DELETE", DELETE);
        valueMap.put("HEAD", HEAD);
        valueMap.put("CONNECT", CONNECT);
        valueMap.put("OPTIONS", OPTIONS);
        valueMap.put("PATCH", PATCH);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static HttpMethodEnum constructFromString(String toConvert) throws IOException {
        HttpMethodEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static HttpMethodEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of HttpMethodEnum values to list of string values.
     * @param toConvert The list of HttpMethodEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<HttpMethodEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (HttpMethodEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 