/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for INCOMPATIBLEPARAMETERVALUEERROR type.
 */
public class INCOMPATIBLEPARAMETERVALUEERROR {
    private IncompatibleParameterValue1IssueEnum issue;
    private IncompatibleParameterValue1DescriptionEnum description;

    /**
     * Default constructor.
     */
    public INCOMPATIBLEPARAMETERVALUEERROR() {
    }

    /**
     * Initialization constructor.
     * @param  issue  IncompatibleParameterValue1IssueEnum value for issue.
     * @param  description  IncompatibleParameterValue1DescriptionEnum value for description.
     */
    public INCOMPATIBLEPARAMETERVALUEERROR(
            IncompatibleParameterValue1IssueEnum issue,
            IncompatibleParameterValue1DescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the IncompatibleParameterValue1IssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public IncompatibleParameterValue1IssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for IncompatibleParameterValue1IssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(IncompatibleParameterValue1IssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the IncompatibleParameterValue1DescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public IncompatibleParameterValue1DescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for IncompatibleParameterValue1DescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(IncompatibleParameterValue1DescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this INCOMPATIBLEPARAMETERVALUEERROR into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "INCOMPATIBLEPARAMETERVALUEERROR [" + "issue=" + issue + ", description="
                + description + "]";
    }

    /**
     * Builds a new {@link INCOMPATIBLEPARAMETERVALUEERROR.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link INCOMPATIBLEPARAMETERVALUEERROR.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link INCOMPATIBLEPARAMETERVALUEERROR}.
     */
    public static class Builder {
        private IncompatibleParameterValue1IssueEnum issue;
        private IncompatibleParameterValue1DescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  IncompatibleParameterValue1IssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(IncompatibleParameterValue1IssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  IncompatibleParameterValue1DescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(IncompatibleParameterValue1DescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link INCOMPATIBLEPARAMETERVALUEERROR} object using the set fields.
         * @return {@link INCOMPATIBLEPARAMETERVALUEERROR}
         */
        public INCOMPATIBLEPARAMETERVALUEERROR build() {
            return new INCOMPATIBLEPARAMETERVALUEERROR(issue, description);
        }
    }
}
