/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * InvalidIbanDescriptionEnum to be used.
 */
public enum InvalidIbanDescriptionEnum {
    ENUM_IBAN_PROVIDED_IS_NOT_A_VALID_BANK_ACCOUNT_NUMBER;


    private static TreeMap<String, InvalidIbanDescriptionEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_IBAN_PROVIDED_IS_NOT_A_VALID_BANK_ACCOUNT_NUMBER.value = "IBAN provided is not a valid bank account number.";

        valueMap.put("IBAN provided is not a valid bank account number.", ENUM_IBAN_PROVIDED_IS_NOT_A_VALID_BANK_ACCOUNT_NUMBER);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static InvalidIbanDescriptionEnum constructFromString(String toConvert) throws IOException {
        InvalidIbanDescriptionEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static InvalidIbanDescriptionEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of InvalidIbanDescriptionEnum values to list of string values.
     * @param toConvert The list of InvalidIbanDescriptionEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<InvalidIbanDescriptionEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (InvalidIbanDescriptionEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 