/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for INVALIDSTRINGLENGTHPayments type.
 */
public class INVALIDSTRINGLENGTHPayments {
    private InvalidStringLengthIssueEnum issue;
    private InvalidStringLengthDescriptionEnum description;

    /**
     * Default constructor.
     */
    public INVALIDSTRINGLENGTHPayments() {
    }

    /**
     * Initialization constructor.
     * @param  issue  InvalidStringLengthIssueEnum value for issue.
     * @param  description  InvalidStringLengthDescriptionEnum value for description.
     */
    public INVALIDSTRINGLENGTHPayments(
            InvalidStringLengthIssueEnum issue,
            InvalidStringLengthDescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the InvalidStringLengthIssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public InvalidStringLengthIssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for InvalidStringLengthIssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(InvalidStringLengthIssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the InvalidStringLengthDescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public InvalidStringLengthDescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for InvalidStringLengthDescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(InvalidStringLengthDescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this INVALIDSTRINGLENGTHPayments into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "INVALIDSTRINGLENGTHPayments [" + "issue=" + issue + ", description=" + description
                + "]";
    }

    /**
     * Builds a new {@link INVALIDSTRINGLENGTHPayments.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link INVALIDSTRINGLENGTHPayments.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link INVALIDSTRINGLENGTHPayments}.
     */
    public static class Builder {
        private InvalidStringLengthIssueEnum issue;
        private InvalidStringLengthDescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  InvalidStringLengthIssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(InvalidStringLengthIssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  InvalidStringLengthDescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(InvalidStringLengthDescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link INVALIDSTRINGLENGTHPayments} object using the set fields.
         * @return {@link INVALIDSTRINGLENGTHPayments}
         */
        public INVALIDSTRINGLENGTHPayments build() {
            return new INVALIDSTRINGLENGTHPayments(issue, description);
        }
    }
}
