/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * InvalidExpiryDateDescriptionEnum to be used.
 */
public enum InvalidExpiryDateDescriptionEnum {
    ENUM_EXPIRY_DATE_IS_INVALID_EXPIRY_DATE_SHOULD_BE_A_DATE_IN_FUTURE_AND_WITHIN_THE_THRESHOLD_FOR_THE_PAYMENT_SOURCE;


    private static TreeMap<String, InvalidExpiryDateDescriptionEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_EXPIRY_DATE_IS_INVALID_EXPIRY_DATE_SHOULD_BE_A_DATE_IN_FUTURE_AND_WITHIN_THE_THRESHOLD_FOR_THE_PAYMENT_SOURCE.value = "Expiry date is invalid. Expiry date should be a date in future and within the threshold for the payment source.";

        valueMap.put("Expiry date is invalid. Expiry date should be a date in future and within the threshold for the payment source.", ENUM_EXPIRY_DATE_IS_INVALID_EXPIRY_DATE_SHOULD_BE_A_DATE_IN_FUTURE_AND_WITHIN_THE_THRESHOLD_FOR_THE_PAYMENT_SOURCE);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static InvalidExpiryDateDescriptionEnum constructFromString(String toConvert) throws IOException {
        InvalidExpiryDateDescriptionEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static InvalidExpiryDateDescriptionEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of InvalidExpiryDateDescriptionEnum values to list of string values.
     * @param toConvert The list of InvalidExpiryDateDescriptionEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<InvalidExpiryDateDescriptionEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (InvalidExpiryDateDescriptionEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 