/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for INVALIDIBANERROR type.
 */
public class INVALIDIBANERROR {
    private InvalidIban1IssueEnum issue;
    private InvalidIban1DescriptionEnum description;

    /**
     * Default constructor.
     */
    public INVALIDIBANERROR() {
    }

    /**
     * Initialization constructor.
     * @param  issue  InvalidIban1IssueEnum value for issue.
     * @param  description  InvalidIban1DescriptionEnum value for description.
     */
    public INVALIDIBANERROR(
            InvalidIban1IssueEnum issue,
            InvalidIban1DescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the InvalidIban1IssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public InvalidIban1IssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for InvalidIban1IssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(InvalidIban1IssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the InvalidIban1DescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public InvalidIban1DescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for InvalidIban1DescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(InvalidIban1DescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this INVALIDIBANERROR into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "INVALIDIBANERROR [" + "issue=" + issue + ", description=" + description + "]";
    }

    /**
     * Builds a new {@link INVALIDIBANERROR.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link INVALIDIBANERROR.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link INVALIDIBANERROR}.
     */
    public static class Builder {
        private InvalidIban1IssueEnum issue;
        private InvalidIban1DescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  InvalidIban1IssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(InvalidIban1IssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  InvalidIban1DescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(InvalidIban1DescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link INVALIDIBANERROR} object using the set fields.
         * @return {@link INVALIDIBANERROR}
         */
        public INVALIDIBANERROR build() {
            return new INVALIDIBANERROR(issue, description);
        }
    }
}
