/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * ItemSkuMismatchIssueEnum to be used.
 */
public enum ItemSkuMismatchIssueEnum {
    ITEM_SKU_MISMATCH;


    private static TreeMap<String, ItemSkuMismatchIssueEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ITEM_SKU_MISMATCH.value = "ITEM_SKU_MISMATCH";

        valueMap.put("ITEM_SKU_MISMATCH", ITEM_SKU_MISMATCH);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static ItemSkuMismatchIssueEnum constructFromString(String toConvert) throws IOException {
        ItemSkuMismatchIssueEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static ItemSkuMismatchIssueEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of ItemSkuMismatchIssueEnum values to list of string values.
     * @param toConvert The list of ItemSkuMismatchIssueEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<ItemSkuMismatchIssueEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (ItemSkuMismatchIssueEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 