/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ITEMSKUMISMATCHERROR type.
 */
public class ITEMSKUMISMATCHERROR {
    private ItemSkuMismatch1IssueEnum issue;
    private ItemSkuMismatch1DescriptionEnum description;

    /**
     * Default constructor.
     */
    public ITEMSKUMISMATCHERROR() {
    }

    /**
     * Initialization constructor.
     * @param  issue  ItemSkuMismatch1IssueEnum value for issue.
     * @param  description  ItemSkuMismatch1DescriptionEnum value for description.
     */
    public ITEMSKUMISMATCHERROR(
            ItemSkuMismatch1IssueEnum issue,
            ItemSkuMismatch1DescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the ItemSkuMismatch1IssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ItemSkuMismatch1IssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for ItemSkuMismatch1IssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(ItemSkuMismatch1IssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the ItemSkuMismatch1DescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ItemSkuMismatch1DescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for ItemSkuMismatch1DescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(ItemSkuMismatch1DescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this ITEMSKUMISMATCHERROR into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ITEMSKUMISMATCHERROR [" + "issue=" + issue + ", description=" + description + "]";
    }

    /**
     * Builds a new {@link ITEMSKUMISMATCHERROR.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ITEMSKUMISMATCHERROR.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link ITEMSKUMISMATCHERROR}.
     */
    public static class Builder {
        private ItemSkuMismatch1IssueEnum issue;
        private ItemSkuMismatch1DescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  ItemSkuMismatch1IssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(ItemSkuMismatch1IssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  ItemSkuMismatch1DescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(ItemSkuMismatch1DescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link ITEMSKUMISMATCHERROR} object using the set fields.
         * @return {@link ITEMSKUMISMATCHERROR}
         */
        public ITEMSKUMISMATCHERROR build() {
            return new ITEMSKUMISMATCHERROR(issue, description);
        }
    }
}
