/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * MaxCaptureAmountExceededIssueEnum to be used.
 */
public enum MaxCaptureAmountExceededIssueEnum {
    MAX_CAPTURE_AMOUNT_EXCEEDED;


    private static TreeMap<String, MaxCaptureAmountExceededIssueEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        MAX_CAPTURE_AMOUNT_EXCEEDED.value = "MAX_CAPTURE_AMOUNT_EXCEEDED";

        valueMap.put("MAX_CAPTURE_AMOUNT_EXCEEDED", MAX_CAPTURE_AMOUNT_EXCEEDED);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static MaxCaptureAmountExceededIssueEnum constructFromString(String toConvert) throws IOException {
        MaxCaptureAmountExceededIssueEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static MaxCaptureAmountExceededIssueEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of MaxCaptureAmountExceededIssueEnum values to list of string values.
     * @param toConvert The list of MaxCaptureAmountExceededIssueEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<MaxCaptureAmountExceededIssueEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (MaxCaptureAmountExceededIssueEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 