/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for MAXNUMBEROFREFUNDSEXCEEDED type.
 */
public class MAXNUMBEROFREFUNDSEXCEEDED {
    private CapturesRefund422IssuesItemsAnyof14IssueEnum issue;
    private CapturesRefund422IssuesItemsAnyof14DescriptionEnum description;

    /**
     * Default constructor.
     */
    public MAXNUMBEROFREFUNDSEXCEEDED() {
    }

    /**
     * Initialization constructor.
     * @param  issue  CapturesRefund422IssuesItemsAnyof14IssueEnum value for issue.
     * @param  description  CapturesRefund422IssuesItemsAnyof14DescriptionEnum value for
     *         description.
     */
    public MAXNUMBEROFREFUNDSEXCEEDED(
            CapturesRefund422IssuesItemsAnyof14IssueEnum issue,
            CapturesRefund422IssuesItemsAnyof14DescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the CapturesRefund422IssuesItemsAnyof14IssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CapturesRefund422IssuesItemsAnyof14IssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for CapturesRefund422IssuesItemsAnyof14IssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(CapturesRefund422IssuesItemsAnyof14IssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the CapturesRefund422IssuesItemsAnyof14DescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CapturesRefund422IssuesItemsAnyof14DescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for CapturesRefund422IssuesItemsAnyof14DescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(CapturesRefund422IssuesItemsAnyof14DescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this MAXNUMBEROFREFUNDSEXCEEDED into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MAXNUMBEROFREFUNDSEXCEEDED [" + "issue=" + issue + ", description=" + description
                + "]";
    }

    /**
     * Builds a new {@link MAXNUMBEROFREFUNDSEXCEEDED.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MAXNUMBEROFREFUNDSEXCEEDED.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link MAXNUMBEROFREFUNDSEXCEEDED}.
     */
    public static class Builder {
        private CapturesRefund422IssuesItemsAnyof14IssueEnum issue;
        private CapturesRefund422IssuesItemsAnyof14DescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  CapturesRefund422IssuesItemsAnyof14IssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(CapturesRefund422IssuesItemsAnyof14IssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  CapturesRefund422IssuesItemsAnyof14DescriptionEnum value for
         *         description.
         * @return Builder
         */
        public Builder description(
                CapturesRefund422IssuesItemsAnyof14DescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link MAXNUMBEROFREFUNDSEXCEEDED} object using the set fields.
         * @return {@link MAXNUMBEROFREFUNDSEXCEEDED}
         */
        public MAXNUMBEROFREFUNDSEXCEEDED build() {
            return new MAXNUMBEROFREFUNDSEXCEEDED(issue, description);
        }
    }
}
