/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for MERCHANTAUTHRESULTSERROR type.
 */
public class MERCHANTAUTHRESULTSERROR {
    private MerchantInitiatedAuthWithResultsEnum issue;
    private ErrMerchInitAuthResults3dsInvalidEnum description;

    /**
     * Default constructor.
     */
    public MERCHANTAUTHRESULTSERROR() {
    }

    /**
     * Initialization constructor.
     * @param  issue  MerchantInitiatedAuthWithResultsEnum value for issue.
     * @param  description  ErrMerchInitAuthResults3dsInvalidEnum value for description.
     */
    public MERCHANTAUTHRESULTSERROR(
            MerchantInitiatedAuthWithResultsEnum issue,
            ErrMerchInitAuthResults3dsInvalidEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the MerchantInitiatedAuthWithResultsEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public MerchantInitiatedAuthWithResultsEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for MerchantInitiatedAuthWithResultsEnum
     */
    @JsonSetter("issue")
    public void setIssue(MerchantInitiatedAuthWithResultsEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the ErrMerchInitAuthResults3dsInvalidEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ErrMerchInitAuthResults3dsInvalidEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for ErrMerchInitAuthResults3dsInvalidEnum
     */
    @JsonSetter("description")
    public void setDescription(ErrMerchInitAuthResults3dsInvalidEnum description) {
        this.description = description;
    }

    /**
     * Converts this MERCHANTAUTHRESULTSERROR into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MERCHANTAUTHRESULTSERROR [" + "issue=" + issue + ", description=" + description
                + "]";
    }

    /**
     * Builds a new {@link MERCHANTAUTHRESULTSERROR.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MERCHANTAUTHRESULTSERROR.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link MERCHANTAUTHRESULTSERROR}.
     */
    public static class Builder {
        private MerchantInitiatedAuthWithResultsEnum issue;
        private ErrMerchInitAuthResults3dsInvalidEnum description;



        /**
         * Setter for issue.
         * @param  issue  MerchantInitiatedAuthWithResultsEnum value for issue.
         * @return Builder
         */
        public Builder issue(MerchantInitiatedAuthWithResultsEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  ErrMerchInitAuthResults3dsInvalidEnum value for description.
         * @return Builder
         */
        public Builder description(ErrMerchInitAuthResults3dsInvalidEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link MERCHANTAUTHRESULTSERROR} object using the set fields.
         * @return {@link MERCHANTAUTHRESULTSERROR}
         */
        public MERCHANTAUTHRESULTSERROR build() {
            return new MERCHANTAUTHRESULTSERROR(issue, description);
        }
    }
}
