/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * MissingRequiredParameterDescription3Enum to be used.
 */
public enum MissingRequiredParameterDescription3Enum {
    ENUM_A_REQUIRED_FIELD_PARAMETER_IS_MISSING;


    private static TreeMap<String, MissingRequiredParameterDescription3Enum> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_A_REQUIRED_FIELD_PARAMETER_IS_MISSING.value = "A required field / parameter is missing.";

        valueMap.put("A required field / parameter is missing.", ENUM_A_REQUIRED_FIELD_PARAMETER_IS_MISSING);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static MissingRequiredParameterDescription3Enum constructFromString(String toConvert) throws IOException {
        MissingRequiredParameterDescription3Enum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static MissingRequiredParameterDescription3Enum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of MissingRequiredParameterDescription3Enum values to list of string values.
     * @param toConvert The list of MissingRequiredParameterDescription3Enum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<MissingRequiredParameterDescription3Enum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (MissingRequiredParameterDescription3Enum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 