/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for MULTIPURCHASEUNITSERROR type.
 */
public class MULTIPURCHASEUNITSERROR {
    private MerchantInitiatedMultiplePurchaseUnitsIssueEnum issue;
    private ErrMerchInitMultiUnitsNotSupportedEnum description;

    /**
     * Default constructor.
     */
    public MULTIPURCHASEUNITSERROR() {
    }

    /**
     * Initialization constructor.
     * @param  issue  MerchantInitiatedMultiplePurchaseUnitsIssueEnum value for issue.
     * @param  description  ErrMerchInitMultiUnitsNotSupportedEnum value for description.
     */
    public MULTIPURCHASEUNITSERROR(
            MerchantInitiatedMultiplePurchaseUnitsIssueEnum issue,
            ErrMerchInitMultiUnitsNotSupportedEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the MerchantInitiatedMultiplePurchaseUnitsIssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public MerchantInitiatedMultiplePurchaseUnitsIssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for MerchantInitiatedMultiplePurchaseUnitsIssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(MerchantInitiatedMultiplePurchaseUnitsIssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the ErrMerchInitMultiUnitsNotSupportedEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ErrMerchInitMultiUnitsNotSupportedEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for ErrMerchInitMultiUnitsNotSupportedEnum
     */
    @JsonSetter("description")
    public void setDescription(ErrMerchInitMultiUnitsNotSupportedEnum description) {
        this.description = description;
    }

    /**
     * Converts this MULTIPURCHASEUNITSERROR into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MULTIPURCHASEUNITSERROR [" + "issue=" + issue + ", description=" + description
                + "]";
    }

    /**
     * Builds a new {@link MULTIPURCHASEUNITSERROR.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MULTIPURCHASEUNITSERROR.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link MULTIPURCHASEUNITSERROR}.
     */
    public static class Builder {
        private MerchantInitiatedMultiplePurchaseUnitsIssueEnum issue;
        private ErrMerchInitMultiUnitsNotSupportedEnum description;



        /**
         * Setter for issue.
         * @param  issue  MerchantInitiatedMultiplePurchaseUnitsIssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(MerchantInitiatedMultiplePurchaseUnitsIssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  ErrMerchInitMultiUnitsNotSupportedEnum value for description.
         * @return Builder
         */
        public Builder description(ErrMerchInitMultiUnitsNotSupportedEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link MULTIPURCHASEUNITSERROR} object using the set fields.
         * @return {@link MULTIPURCHASEUNITSERROR}
         */
        public MULTIPURCHASEUNITSERROR build() {
            return new MULTIPURCHASEUNITSERROR(issue, description);
        }
    }
}
