/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for MULTICURRENCYORDER type.
 */
public class MULTICURRENCYORDER {
    private MultiCurrencyOrderIssueEnum issue;
    private MultiCurrencyOrderDescriptionEnum description;

    /**
     * Default constructor.
     */
    public MULTICURRENCYORDER() {
    }

    /**
     * Initialization constructor.
     * @param  issue  MultiCurrencyOrderIssueEnum value for issue.
     * @param  description  MultiCurrencyOrderDescriptionEnum value for description.
     */
    public MULTICURRENCYORDER(
            MultiCurrencyOrderIssueEnum issue,
            MultiCurrencyOrderDescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the MultiCurrencyOrderIssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public MultiCurrencyOrderIssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for MultiCurrencyOrderIssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(MultiCurrencyOrderIssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the MultiCurrencyOrderDescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public MultiCurrencyOrderDescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for MultiCurrencyOrderDescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(MultiCurrencyOrderDescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this MULTICURRENCYORDER into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MULTICURRENCYORDER [" + "issue=" + issue + ", description=" + description + "]";
    }

    /**
     * Builds a new {@link MULTICURRENCYORDER.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MULTICURRENCYORDER.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link MULTICURRENCYORDER}.
     */
    public static class Builder {
        private MultiCurrencyOrderIssueEnum issue;
        private MultiCurrencyOrderDescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  MultiCurrencyOrderIssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(MultiCurrencyOrderIssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  MultiCurrencyOrderDescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(MultiCurrencyOrderDescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link MULTICURRENCYORDER} object using the set fields.
         * @return {@link MULTICURRENCYORDER}
         */
        public MULTICURRENCYORDER build() {
            return new MULTICURRENCYORDER(issue, description);
        }
    }
}
