/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for MULTIPLESHIPPINGOPTIONSELECTED type.
 */
public class MULTIPLESHIPPINGOPTIONSELECTED {
    private MultipleShippingOptionSelectedIssueEnum issue;
    private MultipleShippingOptionSelectedDescriptionEnum description;

    /**
     * Default constructor.
     */
    public MULTIPLESHIPPINGOPTIONSELECTED() {
    }

    /**
     * Initialization constructor.
     * @param  issue  MultipleShippingOptionSelectedIssueEnum value for issue.
     * @param  description  MultipleShippingOptionSelectedDescriptionEnum value for description.
     */
    public MULTIPLESHIPPINGOPTIONSELECTED(
            MultipleShippingOptionSelectedIssueEnum issue,
            MultipleShippingOptionSelectedDescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the MultipleShippingOptionSelectedIssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public MultipleShippingOptionSelectedIssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for MultipleShippingOptionSelectedIssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(MultipleShippingOptionSelectedIssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the MultipleShippingOptionSelectedDescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public MultipleShippingOptionSelectedDescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for MultipleShippingOptionSelectedDescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(MultipleShippingOptionSelectedDescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this MULTIPLESHIPPINGOPTIONSELECTED into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MULTIPLESHIPPINGOPTIONSELECTED [" + "issue=" + issue + ", description="
                + description + "]";
    }

    /**
     * Builds a new {@link MULTIPLESHIPPINGOPTIONSELECTED.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MULTIPLESHIPPINGOPTIONSELECTED.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link MULTIPLESHIPPINGOPTIONSELECTED}.
     */
    public static class Builder {
        private MultipleShippingOptionSelectedIssueEnum issue;
        private MultipleShippingOptionSelectedDescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  MultipleShippingOptionSelectedIssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(MultipleShippingOptionSelectedIssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  MultipleShippingOptionSelectedDescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(MultipleShippingOptionSelectedDescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link MULTIPLESHIPPINGOPTIONSELECTED} object using the set fields.
         * @return {@link MULTIPLESHIPPINGOPTIONSELECTED}
         */
        public MULTIPLESHIPPINGOPTIONSELECTED build() {
            return new MULTIPLESHIPPINGOPTIONSELECTED(issue, description);
        }
    }
}
