/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for NOTENABLEDFORCARDPROCESSING type.
 */
public class NOTENABLEDFORCARDPROCESSING {
    private NotEnabledForCardProcessingIssueEnum issue;
    private String description;

    /**
     * Default constructor.
     */
    public NOTENABLEDFORCARDPROCESSING() {
    }

    /**
     * Initialization constructor.
     * @param  issue  NotEnabledForCardProcessingIssueEnum value for issue.
     * @param  description  String value for description.
     */
    public NOTENABLEDFORCARDPROCESSING(
            NotEnabledForCardProcessingIssueEnum issue,
            String description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the NotEnabledForCardProcessingIssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public NotEnabledForCardProcessingIssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for NotEnabledForCardProcessingIssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(NotEnabledForCardProcessingIssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the String
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Converts this NOTENABLEDFORCARDPROCESSING into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "NOTENABLEDFORCARDPROCESSING [" + "issue=" + issue + ", description=" + description
                + "]";
    }

    /**
     * Builds a new {@link NOTENABLEDFORCARDPROCESSING.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link NOTENABLEDFORCARDPROCESSING.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link NOTENABLEDFORCARDPROCESSING}.
     */
    public static class Builder {
        private NotEnabledForCardProcessingIssueEnum issue;
        private String description;



        /**
         * Setter for issue.
         * @param  issue  NotEnabledForCardProcessingIssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(NotEnabledForCardProcessingIssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link NOTENABLEDFORCARDPROCESSING} object using the set fields.
         * @return {@link NOTENABLEDFORCARDPROCESSING}
         */
        public NOTENABLEDFORCARDPROCESSING build() {
            return new NOTENABLEDFORCARDPROCESSING(issue, description);
        }
    }
}
