/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * NotEligibleForPnrefProcessing2DescriptionEnum to be used.
 */
public enum NotEligibleForPnrefProcessing2DescriptionEnum {
    ENUM_API_CALLER_IS_NOT_ENABLED_TO_PROCESS_PAYMENTS_WITH_THE_PNREF_PLEASE_CONTACT_CUSTOMER_SUPPORT_TO_REQUEST_PERMISSIONS_TO_PROCESS_TRANSACTIONS_WITH_PNREF;


    private static TreeMap<String, NotEligibleForPnrefProcessing2DescriptionEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_API_CALLER_IS_NOT_ENABLED_TO_PROCESS_PAYMENTS_WITH_THE_PNREF_PLEASE_CONTACT_CUSTOMER_SUPPORT_TO_REQUEST_PERMISSIONS_TO_PROCESS_TRANSACTIONS_WITH_PNREF.value = "API caller is not enabled to process payments with the `pnref`. Please contact customer support to request permissions to process transactions with PNREF.";

        valueMap.put("API caller is not enabled to process payments with the `pnref`. Please contact customer support to request permissions to process transactions with PNREF.", ENUM_API_CALLER_IS_NOT_ENABLED_TO_PROCESS_PAYMENTS_WITH_THE_PNREF_PLEASE_CONTACT_CUSTOMER_SUPPORT_TO_REQUEST_PERMISSIONS_TO_PROCESS_TRANSACTIONS_WITH_PNREF);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static NotEligibleForPnrefProcessing2DescriptionEnum constructFromString(String toConvert) throws IOException {
        NotEligibleForPnrefProcessing2DescriptionEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static NotEligibleForPnrefProcessing2DescriptionEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of NotEligibleForPnrefProcessing2DescriptionEnum values to list of string values.
     * @param toConvert The list of NotEligibleForPnrefProcessing2DescriptionEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<NotEligibleForPnrefProcessing2DescriptionEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (NotEligibleForPnrefProcessing2DescriptionEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 