/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ORDERCOMPLETIONINPROGRESS type.
 */
public class ORDERCOMPLETIONINPROGRESS {
    private OrderCompletionInProgressIssueEnum issue;
    private OrderCompletionInProgressDescriptionEnum description;

    /**
     * Default constructor.
     */
    public ORDERCOMPLETIONINPROGRESS() {
    }

    /**
     * Initialization constructor.
     * @param  issue  OrderCompletionInProgressIssueEnum value for issue.
     * @param  description  OrderCompletionInProgressDescriptionEnum value for description.
     */
    public ORDERCOMPLETIONINPROGRESS(
            OrderCompletionInProgressIssueEnum issue,
            OrderCompletionInProgressDescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the OrderCompletionInProgressIssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public OrderCompletionInProgressIssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for OrderCompletionInProgressIssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(OrderCompletionInProgressIssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the OrderCompletionInProgressDescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public OrderCompletionInProgressDescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for OrderCompletionInProgressDescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(OrderCompletionInProgressDescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this ORDERCOMPLETIONINPROGRESS into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ORDERCOMPLETIONINPROGRESS [" + "issue=" + issue + ", description=" + description
                + "]";
    }

    /**
     * Builds a new {@link ORDERCOMPLETIONINPROGRESS.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ORDERCOMPLETIONINPROGRESS.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link ORDERCOMPLETIONINPROGRESS}.
     */
    public static class Builder {
        private OrderCompletionInProgressIssueEnum issue;
        private OrderCompletionInProgressDescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  OrderCompletionInProgressIssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(OrderCompletionInProgressIssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  OrderCompletionInProgressDescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(OrderCompletionInProgressDescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link ORDERCOMPLETIONINPROGRESS} object using the set fields.
         * @return {@link ORDERCOMPLETIONINPROGRESS}
         */
        public ORDERCOMPLETIONINPROGRESS build() {
            return new ORDERCOMPLETIONINPROGRESS(issue, description);
        }
    }
}
