/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.paypal.sandbox.apim.models.containers.OrdersTrackersPatch422IssuesItems;
import java.util.List;

/**
 * This is a model class for OrdersTrackersPatch422 type.
 */
public class OrdersTrackersPatch422 {
    private List<OrdersTrackersPatch422IssuesItems> issues;

    /**
     * Default constructor.
     */
    public OrdersTrackersPatch422() {
    }

    /**
     * Initialization constructor.
     * @param  issues  List of OrdersTrackersPatch422IssuesItems value for issues.
     */
    public OrdersTrackersPatch422(
            List<OrdersTrackersPatch422IssuesItems> issues) {
        this.issues = issues;
    }

    /**
     * Getter for Issues.
     * @return Returns the List of OrdersTrackersPatch422IssuesItems
     */
    @JsonGetter("issues")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<OrdersTrackersPatch422IssuesItems> getIssues() {
        return issues;
    }

    /**
     * Setter for Issues.
     * @param issues Value for List of OrdersTrackersPatch422IssuesItems
     */
    @JsonSetter("issues")
    public void setIssues(List<OrdersTrackersPatch422IssuesItems> issues) {
        this.issues = issues;
    }

    /**
     * Converts this OrdersTrackersPatch422 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "OrdersTrackersPatch422 [" + "issues=" + issues + "]";
    }

    /**
     * Builds a new {@link OrdersTrackersPatch422.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link OrdersTrackersPatch422.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issues(getIssues());
        return builder;
    }

    /**
     * Class to build instances of {@link OrdersTrackersPatch422}.
     */
    public static class Builder {
        private List<OrdersTrackersPatch422IssuesItems> issues;



        /**
         * Setter for issues.
         * @param  issues  List of OrdersTrackersPatch422IssuesItems value for issues.
         * @return Builder
         */
        public Builder issues(List<OrdersTrackersPatch422IssuesItems> issues) {
            this.issues = issues;
            return this;
        }

        /**
         * Builds a new {@link OrdersTrackersPatch422} object using the set fields.
         * @return {@link OrdersTrackersPatch422}
         */
        public OrdersTrackersPatch422 build() {
            return new OrdersTrackersPatch422(issues);
        }
    }
}
