/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * PayeeAccountNotVerifiedIssueEnum to be used.
 */
public enum PayeeAccountNotVerifiedIssueEnum {
    PAYEE_ACCOUNT_NOT_VERIFIED;


    private static TreeMap<String, PayeeAccountNotVerifiedIssueEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        PAYEE_ACCOUNT_NOT_VERIFIED.value = "PAYEE_ACCOUNT_NOT_VERIFIED";

        valueMap.put("PAYEE_ACCOUNT_NOT_VERIFIED", PAYEE_ACCOUNT_NOT_VERIFIED);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static PayeeAccountNotVerifiedIssueEnum constructFromString(String toConvert) throws IOException {
        PayeeAccountNotVerifiedIssueEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static PayeeAccountNotVerifiedIssueEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of PayeeAccountNotVerifiedIssueEnum values to list of string values.
     * @param toConvert The list of PayeeAccountNotVerifiedIssueEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<PayeeAccountNotVerifiedIssueEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (PayeeAccountNotVerifiedIssueEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 