/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * PayeeAccountNotVerifiedDescriptionEnum to be used.
 */
public enum PayeeAccountNotVerifiedDescriptionEnum {
    ENUM_PAYEE_HAS_NOT_VERIFIED_THEIR_ACCOUNT_WITH_PAYPAL_THE_SELECTED_PAYMENT_METHOD_REQUIRES_THE_RECIPIENT_TO_HAVE_A_VERIFIED_PAYPAL_ACCOUNT_BEFORE_TRANSACTIONS_CAN_BE_PROCESSED_ON_THEIR_BEHALF;


    private static TreeMap<String, PayeeAccountNotVerifiedDescriptionEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_PAYEE_HAS_NOT_VERIFIED_THEIR_ACCOUNT_WITH_PAYPAL_THE_SELECTED_PAYMENT_METHOD_REQUIRES_THE_RECIPIENT_TO_HAVE_A_VERIFIED_PAYPAL_ACCOUNT_BEFORE_TRANSACTIONS_CAN_BE_PROCESSED_ON_THEIR_BEHALF.value = "Payee has not verified their account with PayPal. The selected payment method requires the recipient to have a verified PayPal account before transactions can be processed on their behalf.";

        valueMap.put("Payee has not verified their account with PayPal. The selected payment method requires the recipient to have a verified PayPal account before transactions can be processed on their behalf.", ENUM_PAYEE_HAS_NOT_VERIFIED_THEIR_ACCOUNT_WITH_PAYPAL_THE_SELECTED_PAYMENT_METHOD_REQUIRES_THE_RECIPIENT_TO_HAVE_A_VERIFIED_PAYPAL_ACCOUNT_BEFORE_TRANSACTIONS_CAN_BE_PROCESSED_ON_THEIR_BEHALF);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static PayeeAccountNotVerifiedDescriptionEnum constructFromString(String toConvert) throws IOException {
        PayeeAccountNotVerifiedDescriptionEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static PayeeAccountNotVerifiedDescriptionEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of PayeeAccountNotVerifiedDescriptionEnum values to list of string values.
     * @param toConvert The list of PayeeAccountNotVerifiedDescriptionEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<PayeeAccountNotVerifiedDescriptionEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (PayeeAccountNotVerifiedDescriptionEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 