/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for PAYERACTIONREQUIREDERROR type.
 */
public class PAYERACTIONREQUIREDERROR {
    private PayerActionRequired1IssueEnum issue;
    private PayerActionRequired1DescriptionEnum description;

    /**
     * Default constructor.
     */
    public PAYERACTIONREQUIREDERROR() {
    }

    /**
     * Initialization constructor.
     * @param  issue  PayerActionRequired1IssueEnum value for issue.
     * @param  description  PayerActionRequired1DescriptionEnum value for description.
     */
    public PAYERACTIONREQUIREDERROR(
            PayerActionRequired1IssueEnum issue,
            PayerActionRequired1DescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the PayerActionRequired1IssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PayerActionRequired1IssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for PayerActionRequired1IssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(PayerActionRequired1IssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the PayerActionRequired1DescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PayerActionRequired1DescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for PayerActionRequired1DescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(PayerActionRequired1DescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this PAYERACTIONREQUIREDERROR into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PAYERACTIONREQUIREDERROR [" + "issue=" + issue + ", description=" + description
                + "]";
    }

    /**
     * Builds a new {@link PAYERACTIONREQUIREDERROR.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PAYERACTIONREQUIREDERROR.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link PAYERACTIONREQUIREDERROR}.
     */
    public static class Builder {
        private PayerActionRequired1IssueEnum issue;
        private PayerActionRequired1DescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  PayerActionRequired1IssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(PayerActionRequired1IssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  PayerActionRequired1DescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(PayerActionRequired1DescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link PAYERACTIONREQUIREDERROR} object using the set fields.
         * @return {@link PAYERACTIONREQUIREDERROR}
         */
        public PAYERACTIONREQUIREDERROR build() {
            return new PAYERACTIONREQUIREDERROR(issue, description);
        }
    }
}
