/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for PAYERACCOUNTLOCKEDORCLOSEDERROR type.
 */
public class PAYERACCOUNTLOCKEDORCLOSEDERROR {
    private PayerAccountLockedOrClosed1IssueEnum issue;
    private PayerAccountLockedOrClosed1DescriptionEnum description;

    /**
     * Default constructor.
     */
    public PAYERACCOUNTLOCKEDORCLOSEDERROR() {
    }

    /**
     * Initialization constructor.
     * @param  issue  PayerAccountLockedOrClosed1IssueEnum value for issue.
     * @param  description  PayerAccountLockedOrClosed1DescriptionEnum value for description.
     */
    public PAYERACCOUNTLOCKEDORCLOSEDERROR(
            PayerAccountLockedOrClosed1IssueEnum issue,
            PayerAccountLockedOrClosed1DescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the PayerAccountLockedOrClosed1IssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PayerAccountLockedOrClosed1IssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for PayerAccountLockedOrClosed1IssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(PayerAccountLockedOrClosed1IssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the PayerAccountLockedOrClosed1DescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PayerAccountLockedOrClosed1DescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for PayerAccountLockedOrClosed1DescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(PayerAccountLockedOrClosed1DescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this PAYERACCOUNTLOCKEDORCLOSEDERROR into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PAYERACCOUNTLOCKEDORCLOSEDERROR [" + "issue=" + issue + ", description="
                + description + "]";
    }

    /**
     * Builds a new {@link PAYERACCOUNTLOCKEDORCLOSEDERROR.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PAYERACCOUNTLOCKEDORCLOSEDERROR.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link PAYERACCOUNTLOCKEDORCLOSEDERROR}.
     */
    public static class Builder {
        private PayerAccountLockedOrClosed1IssueEnum issue;
        private PayerAccountLockedOrClosed1DescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  PayerAccountLockedOrClosed1IssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(PayerAccountLockedOrClosed1IssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  PayerAccountLockedOrClosed1DescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(PayerAccountLockedOrClosed1DescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link PAYERACCOUNTLOCKEDORCLOSEDERROR} object using the set fields.
         * @return {@link PAYERACCOUNTLOCKEDORCLOSEDERROR}
         */
        public PAYERACCOUNTLOCKEDORCLOSEDERROR build() {
            return new PAYERACCOUNTLOCKEDORCLOSEDERROR(issue, description);
        }
    }
}
