/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for PAYEENOTENABLEDFORCARDPROCESSING type.
 */
public class PAYEENOTENABLEDFORCARDPROCESSING {
    private PayeeNotEnabledForCardProcessingIssueEnum issue;
    private PayeeNotEnabledForCardProcessingDescriptionEnum description;

    /**
     * Default constructor.
     */
    public PAYEENOTENABLEDFORCARDPROCESSING() {
    }

    /**
     * Initialization constructor.
     * @param  issue  PayeeNotEnabledForCardProcessingIssueEnum value for issue.
     * @param  description  PayeeNotEnabledForCardProcessingDescriptionEnum value for description.
     */
    public PAYEENOTENABLEDFORCARDPROCESSING(
            PayeeNotEnabledForCardProcessingIssueEnum issue,
            PayeeNotEnabledForCardProcessingDescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the PayeeNotEnabledForCardProcessingIssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PayeeNotEnabledForCardProcessingIssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for PayeeNotEnabledForCardProcessingIssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(PayeeNotEnabledForCardProcessingIssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the PayeeNotEnabledForCardProcessingDescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PayeeNotEnabledForCardProcessingDescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for PayeeNotEnabledForCardProcessingDescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(PayeeNotEnabledForCardProcessingDescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this PAYEENOTENABLEDFORCARDPROCESSING into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PAYEENOTENABLEDFORCARDPROCESSING [" + "issue=" + issue + ", description="
                + description + "]";
    }

    /**
     * Builds a new {@link PAYEENOTENABLEDFORCARDPROCESSING.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PAYEENOTENABLEDFORCARDPROCESSING.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link PAYEENOTENABLEDFORCARDPROCESSING}.
     */
    public static class Builder {
        private PayeeNotEnabledForCardProcessingIssueEnum issue;
        private PayeeNotEnabledForCardProcessingDescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  PayeeNotEnabledForCardProcessingIssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(PayeeNotEnabledForCardProcessingIssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  PayeeNotEnabledForCardProcessingDescriptionEnum value for
         *         description.
         * @return Builder
         */
        public Builder description(PayeeNotEnabledForCardProcessingDescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link PAYEENOTENABLEDFORCARDPROCESSING} object using the set fields.
         * @return {@link PAYEENOTENABLEDFORCARDPROCESSING}
         */
        public PAYEENOTENABLEDFORCARDPROCESSING build() {
            return new PAYEENOTENABLEDFORCARDPROCESSING(issue, description);
        }
    }
}
