/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for PAYPALTRANSACTIONIDEXPIREDERROR type.
 */
public class PAYPALTRANSACTIONIDEXPIREDERROR {
    private PaypalTransactionIdExpired1IssueEnum issue;
    private PaypalTransactionIdExpired1DescriptionEnum description;

    /**
     * Default constructor.
     */
    public PAYPALTRANSACTIONIDEXPIREDERROR() {
    }

    /**
     * Initialization constructor.
     * @param  issue  PaypalTransactionIdExpired1IssueEnum value for issue.
     * @param  description  PaypalTransactionIdExpired1DescriptionEnum value for description.
     */
    public PAYPALTRANSACTIONIDEXPIREDERROR(
            PaypalTransactionIdExpired1IssueEnum issue,
            PaypalTransactionIdExpired1DescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the PaypalTransactionIdExpired1IssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PaypalTransactionIdExpired1IssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for PaypalTransactionIdExpired1IssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(PaypalTransactionIdExpired1IssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the PaypalTransactionIdExpired1DescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PaypalTransactionIdExpired1DescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for PaypalTransactionIdExpired1DescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(PaypalTransactionIdExpired1DescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this PAYPALTRANSACTIONIDEXPIREDERROR into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PAYPALTRANSACTIONIDEXPIREDERROR [" + "issue=" + issue + ", description="
                + description + "]";
    }

    /**
     * Builds a new {@link PAYPALTRANSACTIONIDEXPIREDERROR.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PAYPALTRANSACTIONIDEXPIREDERROR.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link PAYPALTRANSACTIONIDEXPIREDERROR}.
     */
    public static class Builder {
        private PaypalTransactionIdExpired1IssueEnum issue;
        private PaypalTransactionIdExpired1DescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  PaypalTransactionIdExpired1IssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(PaypalTransactionIdExpired1IssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  PaypalTransactionIdExpired1DescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(PaypalTransactionIdExpired1DescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link PAYPALTRANSACTIONIDEXPIREDERROR} object using the set fields.
         * @return {@link PAYPALTRANSACTIONIDEXPIREDERROR}
         */
        public PAYPALTRANSACTIONIDEXPIREDERROR build() {
            return new PAYPALTRANSACTIONIDEXPIREDERROR(issue, description);
        }
    }
}
