/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for PREVIOUSREQUESTINPROGRESS type.
 */
public class PREVIOUSREQUESTINPROGRESS {
    private Conflicterror409responseIssuesItemsAnyof0IssueEnum issue;
    private PreviousRequestInProgressDescriptionEnum description;

    /**
     * Default constructor.
     */
    public PREVIOUSREQUESTINPROGRESS() {
    }

    /**
     * Initialization constructor.
     * @param  issue  Conflicterror409responseIssuesItemsAnyof0IssueEnum value for issue.
     * @param  description  PreviousRequestInProgressDescriptionEnum value for description.
     */
    public PREVIOUSREQUESTINPROGRESS(
            Conflicterror409responseIssuesItemsAnyof0IssueEnum issue,
            PreviousRequestInProgressDescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the Conflicterror409responseIssuesItemsAnyof0IssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Conflicterror409responseIssuesItemsAnyof0IssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for Conflicterror409responseIssuesItemsAnyof0IssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(Conflicterror409responseIssuesItemsAnyof0IssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the PreviousRequestInProgressDescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PreviousRequestInProgressDescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for PreviousRequestInProgressDescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(PreviousRequestInProgressDescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this PREVIOUSREQUESTINPROGRESS into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PREVIOUSREQUESTINPROGRESS [" + "issue=" + issue + ", description=" + description
                + "]";
    }

    /**
     * Builds a new {@link PREVIOUSREQUESTINPROGRESS.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PREVIOUSREQUESTINPROGRESS.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link PREVIOUSREQUESTINPROGRESS}.
     */
    public static class Builder {
        private Conflicterror409responseIssuesItemsAnyof0IssueEnum issue;
        private PreviousRequestInProgressDescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  Conflicterror409responseIssuesItemsAnyof0IssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(Conflicterror409responseIssuesItemsAnyof0IssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  PreviousRequestInProgressDescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(PreviousRequestInProgressDescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link PREVIOUSREQUESTINPROGRESS} object using the set fields.
         * @return {@link PREVIOUSREQUESTINPROGRESS}
         */
        public PREVIOUSREQUESTINPROGRESS build() {
            return new PREVIOUSREQUESTINPROGRESS(issue, description);
        }
    }
}
