/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for REFERENCEIDREQUIRED type.
 */
public class REFERENCEIDREQUIRED {
    private ReferenceIdRequiredIssueEnum issue;
    private ReferenceIdRequiredDescriptionEnum description;

    /**
     * Default constructor.
     */
    public REFERENCEIDREQUIRED() {
    }

    /**
     * Initialization constructor.
     * @param  issue  ReferenceIdRequiredIssueEnum value for issue.
     * @param  description  ReferenceIdRequiredDescriptionEnum value for description.
     */
    public REFERENCEIDREQUIRED(
            ReferenceIdRequiredIssueEnum issue,
            ReferenceIdRequiredDescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the ReferenceIdRequiredIssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ReferenceIdRequiredIssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for ReferenceIdRequiredIssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(ReferenceIdRequiredIssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the ReferenceIdRequiredDescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ReferenceIdRequiredDescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for ReferenceIdRequiredDescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(ReferenceIdRequiredDescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this REFERENCEIDREQUIRED into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "REFERENCEIDREQUIRED [" + "issue=" + issue + ", description=" + description + "]";
    }

    /**
     * Builds a new {@link REFERENCEIDREQUIRED.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link REFERENCEIDREQUIRED.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link REFERENCEIDREQUIRED}.
     */
    public static class Builder {
        private ReferenceIdRequiredIssueEnum issue;
        private ReferenceIdRequiredDescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  ReferenceIdRequiredIssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(ReferenceIdRequiredIssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  ReferenceIdRequiredDescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(ReferenceIdRequiredDescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link REFERENCEIDREQUIRED} object using the set fields.
         * @return {@link REFERENCEIDREQUIRED}
         */
        public REFERENCEIDREQUIRED build() {
            return new REFERENCEIDREQUIRED(issue, description);
        }
    }
}
