/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for REFUNDAMOUNTEXCEEDED type.
 */
public class REFUNDAMOUNTEXCEEDED {
    private CapturesRefund422IssuesItemsAnyof10IssueEnum issue;
    private CapturesRefund422IssuesItemsAnyof10DescriptionEnum description;

    /**
     * Default constructor.
     */
    public REFUNDAMOUNTEXCEEDED() {
    }

    /**
     * Initialization constructor.
     * @param  issue  CapturesRefund422IssuesItemsAnyof10IssueEnum value for issue.
     * @param  description  CapturesRefund422IssuesItemsAnyof10DescriptionEnum value for
     *         description.
     */
    public REFUNDAMOUNTEXCEEDED(
            CapturesRefund422IssuesItemsAnyof10IssueEnum issue,
            CapturesRefund422IssuesItemsAnyof10DescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the CapturesRefund422IssuesItemsAnyof10IssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CapturesRefund422IssuesItemsAnyof10IssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for CapturesRefund422IssuesItemsAnyof10IssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(CapturesRefund422IssuesItemsAnyof10IssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the CapturesRefund422IssuesItemsAnyof10DescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CapturesRefund422IssuesItemsAnyof10DescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for CapturesRefund422IssuesItemsAnyof10DescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(CapturesRefund422IssuesItemsAnyof10DescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this REFUNDAMOUNTEXCEEDED into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "REFUNDAMOUNTEXCEEDED [" + "issue=" + issue + ", description=" + description + "]";
    }

    /**
     * Builds a new {@link REFUNDAMOUNTEXCEEDED.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link REFUNDAMOUNTEXCEEDED.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link REFUNDAMOUNTEXCEEDED}.
     */
    public static class Builder {
        private CapturesRefund422IssuesItemsAnyof10IssueEnum issue;
        private CapturesRefund422IssuesItemsAnyof10DescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  CapturesRefund422IssuesItemsAnyof10IssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(CapturesRefund422IssuesItemsAnyof10IssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  CapturesRefund422IssuesItemsAnyof10DescriptionEnum value for
         *         description.
         * @return Builder
         */
        public Builder description(
                CapturesRefund422IssuesItemsAnyof10DescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link REFUNDAMOUNTEXCEEDED} object using the set fields.
         * @return {@link REFUNDAMOUNTEXCEEDED}
         */
        public REFUNDAMOUNTEXCEEDED build() {
            return new REFUNDAMOUNTEXCEEDED(issue, description);
        }
    }
}
