/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * ReturnUrlRequiredDescriptionEnum to be used.
 */
public enum ReturnUrlRequiredDescriptionEnum {
    ENUM_THE_RETURN_URL_IS_REQUIRED_WHEN_ATTEMPTING_TO_VAULT_THIS_SOURCE;


    private static TreeMap<String, ReturnUrlRequiredDescriptionEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_THE_RETURN_URL_IS_REQUIRED_WHEN_ATTEMPTING_TO_VAULT_THIS_SOURCE.value = "The return url is required when attempting to vault this source.";

        valueMap.put("The return url is required when attempting to vault this source.", ENUM_THE_RETURN_URL_IS_REQUIRED_WHEN_ATTEMPTING_TO_VAULT_THIS_SOURCE);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static ReturnUrlRequiredDescriptionEnum constructFromString(String toConvert) throws IOException {
        ReturnUrlRequiredDescriptionEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static ReturnUrlRequiredDescriptionEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of ReturnUrlRequiredDescriptionEnum values to list of string values.
     * @param toConvert The list of ReturnUrlRequiredDescriptionEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<ReturnUrlRequiredDescriptionEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (ReturnUrlRequiredDescriptionEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 