/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * ShippingOptionNotSelectedIssueEnum to be used.
 */
public enum ShippingOptionNotSelectedIssueEnum {
    SHIPPING_OPTION_NOT_SELECTED;


    private static TreeMap<String, ShippingOptionNotSelectedIssueEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        SHIPPING_OPTION_NOT_SELECTED.value = "SHIPPING_OPTION_NOT_SELECTED";

        valueMap.put("SHIPPING_OPTION_NOT_SELECTED", SHIPPING_OPTION_NOT_SELECTED);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static ShippingOptionNotSelectedIssueEnum constructFromString(String toConvert) throws IOException {
        ShippingOptionNotSelectedIssueEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static ShippingOptionNotSelectedIssueEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of ShippingOptionNotSelectedIssueEnum values to list of string values.
     * @param toConvert The list of ShippingOptionNotSelectedIssueEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<ShippingOptionNotSelectedIssueEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (ShippingOptionNotSelectedIssueEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 