/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for SHIPPINGOPTIONNOTSELECTED type.
 */
public class SHIPPINGOPTIONNOTSELECTED {
    private ShippingOptionNotSelectedIssueEnum issue;
    private ShippingOptionNotSelectedDescriptionEnum description;

    /**
     * Default constructor.
     */
    public SHIPPINGOPTIONNOTSELECTED() {
    }

    /**
     * Initialization constructor.
     * @param  issue  ShippingOptionNotSelectedIssueEnum value for issue.
     * @param  description  ShippingOptionNotSelectedDescriptionEnum value for description.
     */
    public SHIPPINGOPTIONNOTSELECTED(
            ShippingOptionNotSelectedIssueEnum issue,
            ShippingOptionNotSelectedDescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the ShippingOptionNotSelectedIssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ShippingOptionNotSelectedIssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for ShippingOptionNotSelectedIssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(ShippingOptionNotSelectedIssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the ShippingOptionNotSelectedDescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ShippingOptionNotSelectedDescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for ShippingOptionNotSelectedDescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(ShippingOptionNotSelectedDescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this SHIPPINGOPTIONNOTSELECTED into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SHIPPINGOPTIONNOTSELECTED [" + "issue=" + issue + ", description=" + description
                + "]";
    }

    /**
     * Builds a new {@link SHIPPINGOPTIONNOTSELECTED.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SHIPPINGOPTIONNOTSELECTED.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link SHIPPINGOPTIONNOTSELECTED}.
     */
    public static class Builder {
        private ShippingOptionNotSelectedIssueEnum issue;
        private ShippingOptionNotSelectedDescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  ShippingOptionNotSelectedIssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(ShippingOptionNotSelectedIssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  ShippingOptionNotSelectedDescriptionEnum value for description.
         * @return Builder
         */
        public Builder description(ShippingOptionNotSelectedDescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link SHIPPINGOPTIONNOTSELECTED} object using the set fields.
         * @return {@link SHIPPINGOPTIONNOTSELECTED}
         */
        public SHIPPINGOPTIONNOTSELECTED build() {
            return new SHIPPINGOPTIONNOTSELECTED(issue, description);
        }
    }
}
