/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for TRANSACTIONRECEIVELIMITEXCEEDEDERRORRESPONSE type.
 */
public class TRANSACTIONRECEIVELIMITEXCEEDEDERRORRESPONSE {
    private TransactionReceivingLimitExceeded2IssueEnum issue;
    private TransactionReceivingLimitExceeded2DescriptionEnum description;

    /**
     * Default constructor.
     */
    public TRANSACTIONRECEIVELIMITEXCEEDEDERRORRESPONSE() {
    }

    /**
     * Initialization constructor.
     * @param  issue  TransactionReceivingLimitExceeded2IssueEnum value for issue.
     * @param  description  TransactionReceivingLimitExceeded2DescriptionEnum value for description.
     */
    public TRANSACTIONRECEIVELIMITEXCEEDEDERRORRESPONSE(
            TransactionReceivingLimitExceeded2IssueEnum issue,
            TransactionReceivingLimitExceeded2DescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the TransactionReceivingLimitExceeded2IssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TransactionReceivingLimitExceeded2IssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for TransactionReceivingLimitExceeded2IssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(TransactionReceivingLimitExceeded2IssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the TransactionReceivingLimitExceeded2DescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TransactionReceivingLimitExceeded2DescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for TransactionReceivingLimitExceeded2DescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(TransactionReceivingLimitExceeded2DescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this TRANSACTIONRECEIVELIMITEXCEEDEDERRORRESPONSE into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TRANSACTIONRECEIVELIMITEXCEEDEDERRORRESPONSE [" + "issue=" + issue
                + ", description=" + description + "]";
    }

    /**
     * Builds a new {@link TRANSACTIONRECEIVELIMITEXCEEDEDERRORRESPONSE.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TRANSACTIONRECEIVELIMITEXCEEDEDERRORRESPONSE.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link TRANSACTIONRECEIVELIMITEXCEEDEDERRORRESPONSE}.
     */
    public static class Builder {
        private TransactionReceivingLimitExceeded2IssueEnum issue;
        private TransactionReceivingLimitExceeded2DescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  TransactionReceivingLimitExceeded2IssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(TransactionReceivingLimitExceeded2IssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  TransactionReceivingLimitExceeded2DescriptionEnum value for
         *         description.
         * @return Builder
         */
        public Builder description(
                TransactionReceivingLimitExceeded2DescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link TRANSACTIONRECEIVELIMITEXCEEDEDERRORRESPONSE} object using the set
         * fields.
         * @return {@link TRANSACTIONRECEIVELIMITEXCEEDEDERRORRESPONSE}
         */
        public TRANSACTIONRECEIVELIMITEXCEEDEDERRORRESPONSE build() {
            return new TRANSACTIONRECEIVELIMITEXCEEDEDERRORRESPONSE(issue, description);
        }
    }
}
