/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * TransactionBlockedByPayeeDescriptionEnum to be used.
 */
public enum TransactionBlockedByPayeeDescriptionEnum {
    ENUM_TRANSACTION_BLOCKED_BY_PAYEES_FRAUD_PROTECTION_SETTINGS;


    private static TreeMap<String, TransactionBlockedByPayeeDescriptionEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_TRANSACTION_BLOCKED_BY_PAYEES_FRAUD_PROTECTION_SETTINGS.value = "Transaction blocked by Payee’s Fraud Protection settings.";

        valueMap.put("Transaction blocked by Payee’s Fraud Protection settings.", ENUM_TRANSACTION_BLOCKED_BY_PAYEES_FRAUD_PROTECTION_SETTINGS);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static TransactionBlockedByPayeeDescriptionEnum constructFromString(String toConvert) throws IOException {
        TransactionBlockedByPayeeDescriptionEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static TransactionBlockedByPayeeDescriptionEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of TransactionBlockedByPayeeDescriptionEnum values to list of string values.
     * @param toConvert The list of TransactionBlockedByPayeeDescriptionEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<TransactionBlockedByPayeeDescriptionEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (TransactionBlockedByPayeeDescriptionEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 