/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for UNSUPPORTEDPROCESSINGINSTRUCTIONERROR type.
 */
public class UNSUPPORTEDPROCESSINGINSTRUCTIONERROR {
    private UnsupportedProcessingInstruction1IssueEnum issue;
    private UnsupportedProcessingInstruction1DescriptionEnum description;

    /**
     * Default constructor.
     */
    public UNSUPPORTEDPROCESSINGINSTRUCTIONERROR() {
    }

    /**
     * Initialization constructor.
     * @param  issue  UnsupportedProcessingInstruction1IssueEnum value for issue.
     * @param  description  UnsupportedProcessingInstruction1DescriptionEnum value for description.
     */
    public UNSUPPORTEDPROCESSINGINSTRUCTIONERROR(
            UnsupportedProcessingInstruction1IssueEnum issue,
            UnsupportedProcessingInstruction1DescriptionEnum description) {
        this.issue = issue;
        this.description = description;
    }

    /**
     * Getter for Issue.
     * @return Returns the UnsupportedProcessingInstruction1IssueEnum
     */
    @JsonGetter("issue")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public UnsupportedProcessingInstruction1IssueEnum getIssue() {
        return issue;
    }

    /**
     * Setter for Issue.
     * @param issue Value for UnsupportedProcessingInstruction1IssueEnum
     */
    @JsonSetter("issue")
    public void setIssue(UnsupportedProcessingInstruction1IssueEnum issue) {
        this.issue = issue;
    }

    /**
     * Getter for Description.
     * @return Returns the UnsupportedProcessingInstruction1DescriptionEnum
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public UnsupportedProcessingInstruction1DescriptionEnum getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for UnsupportedProcessingInstruction1DescriptionEnum
     */
    @JsonSetter("description")
    public void setDescription(UnsupportedProcessingInstruction1DescriptionEnum description) {
        this.description = description;
    }

    /**
     * Converts this UNSUPPORTEDPROCESSINGINSTRUCTIONERROR into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UNSUPPORTEDPROCESSINGINSTRUCTIONERROR [" + "issue=" + issue + ", description="
                + description + "]";
    }

    /**
     * Builds a new {@link UNSUPPORTEDPROCESSINGINSTRUCTIONERROR.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UNSUPPORTEDPROCESSINGINSTRUCTIONERROR.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issue(getIssue())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link UNSUPPORTEDPROCESSINGINSTRUCTIONERROR}.
     */
    public static class Builder {
        private UnsupportedProcessingInstruction1IssueEnum issue;
        private UnsupportedProcessingInstruction1DescriptionEnum description;



        /**
         * Setter for issue.
         * @param  issue  UnsupportedProcessingInstruction1IssueEnum value for issue.
         * @return Builder
         */
        public Builder issue(UnsupportedProcessingInstruction1IssueEnum issue) {
            this.issue = issue;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  UnsupportedProcessingInstruction1DescriptionEnum value for
         *         description.
         * @return Builder
         */
        public Builder description(UnsupportedProcessingInstruction1DescriptionEnum description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link UNSUPPORTEDPROCESSINGINSTRUCTIONERROR} object using the set fields.
         * @return {@link UNSUPPORTEDPROCESSINGINSTRUCTIONERROR}
         */
        public UNSUPPORTEDPROCESSINGINSTRUCTIONERROR build() {
            return new UNSUPPORTEDPROCESSINGINSTRUCTIONERROR(issue, description);
        }
    }
}
