/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * UnsupportedPaymentInstructionDescriptionEnum to be used.
 */
public enum UnsupportedPaymentInstructionDescriptionEnum {
    ENUM_YOU_MUST_PROVIDE_THE_PAYMENT_INSTRUCTION_WHEN_YOU_CAPTURE_AN_AUTHORIZED_PAYMENT_FOR_INTENTAUTHORIZE_FOR_DETAILS_SEE_A_HREFDOCSAPIPAYMENTSV2AUTHORIZATIONS_CAPTURECAPTURE_AUTHORIZATIONA_FOR_INTENTCAPTURE_SEND_THE_PAYMENT_INSTRUCTION_WHEN_YOU_CREATE_THE_ORDER;


    private static TreeMap<String, UnsupportedPaymentInstructionDescriptionEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_YOU_MUST_PROVIDE_THE_PAYMENT_INSTRUCTION_WHEN_YOU_CAPTURE_AN_AUTHORIZED_PAYMENT_FOR_INTENTAUTHORIZE_FOR_DETAILS_SEE_A_HREFDOCSAPIPAYMENTSV2AUTHORIZATIONS_CAPTURECAPTURE_AUTHORIZATIONA_FOR_INTENTCAPTURE_SEND_THE_PAYMENT_INSTRUCTION_WHEN_YOU_CREATE_THE_ORDER.value = "You must provide the payment instruction when you capture an authorized payment for `intent=AUTHORIZE`. For details, see <a href=\"/docs/api/payments/v2/#authorizations_capture\">Capture authorization</a>. For `intent=CAPTURE`, send the payment instruction when you create the order.";

        valueMap.put("You must provide the payment instruction when you capture an authorized payment for `intent=AUTHORIZE`. For details, see <a href=\"/docs/api/payments/v2/#authorizations_capture\">Capture authorization</a>. For `intent=CAPTURE`, send the payment instruction when you create the order.", ENUM_YOU_MUST_PROVIDE_THE_PAYMENT_INSTRUCTION_WHEN_YOU_CAPTURE_AN_AUTHORIZED_PAYMENT_FOR_INTENTAUTHORIZE_FOR_DETAILS_SEE_A_HREFDOCSAPIPAYMENTSV2AUTHORIZATIONS_CAPTURECAPTURE_AUTHORIZATIONA_FOR_INTENTCAPTURE_SEND_THE_PAYMENT_INSTRUCTION_WHEN_YOU_CREATE_THE_ORDER);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static UnsupportedPaymentInstructionDescriptionEnum constructFromString(String toConvert) throws IOException {
        UnsupportedPaymentInstructionDescriptionEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static UnsupportedPaymentInstructionDescriptionEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of UnsupportedPaymentInstructionDescriptionEnum values to list of string values.
     * @param toConvert The list of UnsupportedPaymentInstructionDescriptionEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<UnsupportedPaymentInstructionDescriptionEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (UnsupportedPaymentInstructionDescriptionEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 