/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * VaultInstructionDuplicatedDescriptionEnum to be used.
 */
public enum VaultInstructionDuplicatedDescriptionEnum {
    ENUM_ONLY_ONE_VAULT_INSTRUCTION_IS_ALLOWED_PLEASE_USE_VAULTSTORE_IN_VAULT_TO_PROVIDE_VAULT_INSTRUCTION;


    private static TreeMap<String, VaultInstructionDuplicatedDescriptionEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_ONLY_ONE_VAULT_INSTRUCTION_IS_ALLOWED_PLEASE_USE_VAULTSTORE_IN_VAULT_TO_PROVIDE_VAULT_INSTRUCTION.value = "Only one vault instruction is allowed. Please use `vault.store_in_vault` to provide vault instruction.";

        valueMap.put("Only one vault instruction is allowed. Please use `vault.store_in_vault` to provide vault instruction.", ENUM_ONLY_ONE_VAULT_INSTRUCTION_IS_ALLOWED_PLEASE_USE_VAULTSTORE_IN_VAULT_TO_PROVIDE_VAULT_INSTRUCTION);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static VaultInstructionDuplicatedDescriptionEnum constructFromString(String toConvert) throws IOException {
        VaultInstructionDuplicatedDescriptionEnum enumValue = fromString(toConvert);
        if (enumValue == null)
        {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static VaultInstructionDuplicatedDescriptionEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of VaultInstructionDuplicatedDescriptionEnum values to list of string values.
     * @param toConvert The list of VaultInstructionDuplicatedDescriptionEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<VaultInstructionDuplicatedDescriptionEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (VaultInstructionDuplicatedDescriptionEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 