/*
 * MergedApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.paypal.sandbox.apim.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for VenmoResponseAllof2 type.
 */
public class VenmoResponseAllof2 {
    private String userName;

    /**
     * Default constructor.
     */
    public VenmoResponseAllof2() {
    }

    /**
     * Initialization constructor.
     * @param  userName  String value for userName.
     */
    public VenmoResponseAllof2(
            String userName) {
        this.userName = userName;
    }

    /**
     * Getter for UserName.
     * The Venmo username, as chosen by the user.
     * @return Returns the String
     */
    @JsonGetter("user_name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUserName() {
        return userName;
    }

    /**
     * Setter for UserName.
     * The Venmo username, as chosen by the user.
     * @param userName Value for String
     */
    @JsonSetter("user_name")
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * Converts this VenmoResponseAllof2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "VenmoResponseAllof2 [" + "userName=" + userName + "]";
    }

    /**
     * Builds a new {@link VenmoResponseAllof2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link VenmoResponseAllof2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .userName(getUserName());
        return builder;
    }

    /**
     * Class to build instances of {@link VenmoResponseAllof2}.
     */
    public static class Builder {
        private String userName;



        /**
         * Setter for userName.
         * @param  userName  String value for userName.
         * @return Builder
         */
        public Builder userName(String userName) {
            this.userName = userName;
            return this;
        }

        /**
         * Builds a new {@link VenmoResponseAllof2} object using the set fields.
         * @return {@link VenmoResponseAllof2}
         */
        public VenmoResponseAllof2 build() {
            return new VenmoResponseAllof2(userName);
        }
    }
}
